<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asci</string>
		<string>azkii</string>
		<string>nfo</string>
		<string>info</string>
		<string>diz</string>
	</array>
	<key>name</key>
	<string>Amiga Ascii</string>
	<key>patterns</key>
	<array/>
	<key>scopeName</key>
	<string>source.amiga.ascii</string>
	<key>uuid</key>
	<string>A02C12AF-5137-46F6-8189-0CB14CB64DED</string>
</dict>
</plist>
